a=input("1 chi isimni kiriting: ")
b=input("yana shu isimni kiriting: ")
c=input("2 chi isimni kiriting: ")
d=input("yana shu isimni kiriting: ")
print(a==b and c==d)
e=int(input( "1 chi sonni kiriting: "))
f=int(input( "yana shu sonni kiriting: "))
h=int(input( "2 chi sonni kiriting: "))
j=int(input( "yana shu sonni kiriting: "))
print(e==f or h==j)
l=input( "o'zingizga yoqqn rangni kiriting: ")
m=input( "yana shu rangni kiriting: ")
n=input( "yoqtirmaydigan rangni kiriting: ")
o=input( "yana shu rangni kiriting: ")
print(not l==m, not n==o)